### ISSUE TITLE
Stopped working after upgrading to Android 14

### ISSUE THREAD

**Issue by RiedleroD** [programminghoch10/UpsideWifi#2]
might also be due to me using [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod/) instead of LSPosed… because LSPosed stopped working after I upgraded to android 14.

To be specific, I'm running:
- perseus (Xiaomi Mi Mix 3)
- LineageOS 21 (A14) build 2024.06.30 (20 2023.12.31 before upgrade)
- magisk 27.0 (26.4 before upgrade)
- LSPosed_mod 1.9.3 zygisk variant (LSPosed 1.9.2 before upgrade)
- NikGapps core build 2024.04.20 (2022.08.28 before upgrade)

aside from that, the only changes were other magisk and Xposed modules, but none of them should be relevant to UpsideWifi.

If you need more info from me, I can provide logs and other debug info. I want this funny little module to start working again :3

**Comment by RiedleroD** [comment]
I found some logs:

```
[ 2024-07-01T22:54:17.024    10144:  2563:  2563 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: com.android.systemui:layout/status_bar_wifi_group
	at HqW.Rl.xR.TnXvBrHnNiI.d.ources.hookLayout(SourceFile:7)
	at com.programminghoch10.UpsideWifi.UpsideWifi.handleInitPackageResources(UpsideWifi.java:19)
	at SgJssrSeFn.aBQvaJKQiJa.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(Unknown Source:2)
	at SgJssrSeFn.aBQvaJKQiJa.callbacks.XC_InitPackageResources.call(Unknown Source:6)
	at SgJssrSeFn.aBQvaJKQiJa.callbacks.XCallback.callAll(Unknown Source:26)
	at SgJssrSeFn.aBQvaJKQiJa.XposedInit.cloneToXResources(Unknown Source:64)
	at SgJssrSeFn.aBQvaJKQiJa.XposedInit.c(Unknown Source:0)
	at SgJssrSeFn.aBQvaJKQiJa.XposedInit$2.afterHookedMethod(Unknown Source:34)
	at SgJssrSeFn.aBQvaJKQiJa.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.createResources(Unknown Source:17)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1148)
	at android.app.LoadedApk.getResources(LoadedApk.java:1375)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3336)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3327)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7277)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

similar issue in hangoverclock btw. Interestingly, MobileIconChanger works regardless. Will try to get more info out of this bastard phone

**Comment by programminghoch10** [comment]
Thanks for informing me,
haven't switched to android 14 on my daily driver yet, so I didn't notice.
HangoverClock has a different issue (since android 12, way more complicated to fix), you can open an issue there if you want.

**Comment by RiedleroD** [comment]
…still doesn't work for me, although now it stopped throwing errors

**Comment by RiedleroD** [comment]
oh nevermind a reboot fixed it

**Comment by RiedleroD** [comment]
thanks so much for the incredibly quick fix!
